// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-Sqx8IXJQYsfuJTrtk286g09JqNk6Wc',
    appId: '1:872445800696:web:93283542ab2a51c2270b0d',
    messagingSenderId: '872445800696',
    projectId: 'movie-8a0b2',
    authDomain: 'movie-8a0b2.firebaseapp.com',
    storageBucket: 'movie-8a0b2.appspot.com',
    measurementId: 'G-B3RTSNWB3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACKTuqDG6pHgUxflDkQHbts5zxPllBHf4',
    appId: '1:872445800696:android:4d5bdadb8a9c8c6b270b0d',
    messagingSenderId: '872445800696',
    projectId: 'movie-8a0b2',
    storageBucket: 'movie-8a0b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUkn5CMpSpcbG2P84aZw_OLh5l0sToMFI',
    appId: '1:872445800696:ios:8755ffdc39bd858f270b0d',
    messagingSenderId: '872445800696',
    projectId: 'movie-8a0b2',
    storageBucket: 'movie-8a0b2.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUkn5CMpSpcbG2P84aZw_OLh5l0sToMFI',
    appId: '1:872445800696:ios:8755ffdc39bd858f270b0d',
    messagingSenderId: '872445800696',
    projectId: 'movie-8a0b2',
    storageBucket: 'movie-8a0b2.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-Sqx8IXJQYsfuJTrtk286g09JqNk6Wc',
    appId: '1:872445800696:web:5eb41fb428b2766d270b0d',
    messagingSenderId: '872445800696',
    projectId: 'movie-8a0b2',
    authDomain: 'movie-8a0b2.firebaseapp.com',
    storageBucket: 'movie-8a0b2.appspot.com',
    measurementId: 'G-GH9H53N4NJ',
  );
}
